version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: defaultdb
      POSTGRES_USER: avnadmin
      POSTGRES_PASSWORD: AVNS_XUboo7-5HtovFIYQUMT
    ports:
      - "5432:5432" # Host port mapped to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
